github.com:
    users:
        ReginaldoGonssavre:
            oauth_token: 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
    oauth_token: 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
    user: ReginaldoGonssavre
